# Site
name: "MindSlim"
title: "Treinamento para Coachs de Emagrecimento"
description: "Treinamento para Coachs de Emagrecimento"
meta_description: "Treinamento para Coachs de Emagrecimento"
logo: 'assets/images/logo.png'
baseurl: '/MindSlim'
email: 'arq.rodrigomatos@gmail.com'
google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Plugins
plugins:
  - jekyll-sitemap
  # - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-archives

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge
